apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gss-single-template.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "gss-single-template.selectorLabels" . | nindent 4 }}
  type: ClusterIP
