# Default values for gss-single-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: dev

ingressClassName: koderover-admin-nginx

image:
  repository: ccr.ccs.tencentyun.com/trial/go-sample-site
  pullPolicy: IfNotPresent
  tag: 0.1.0

imagePullSecrets:
  - name: default-registry-secret

nameOverride: 
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

param:
  service: $T-Service$
  project: $T-Project$
  custom: {{.custom}}

github:
  knownHost:
  sshKey:
